DROP TABLE IF EXISTS "books";
CREATE TABLE "books" ("idBook" INTEGER PRIMARY KEY  AUTOINCREMENT  NOT NULL  UNIQUE , "name" VARCHAR NOT NULL , "author" VARCHAR NOT NULL , "edition" INTEGER NOT NULL , "publishing" VARCHAR NOT NULL , "pageNumber" INTEGER NOT NULL );
